PS_MarkerMakerConfig {
 m_mFactionsManualMarkerConfig {
  PS_FactionManualMarkerConfig "{5F34AC07AA3094AD}" {
   m_mManualMarkerConfig PS_ManualMarkerConfig "{5F34AC07AD94EA59}" {
    m_aVisibleForFactions {
     "USSR"
    }
    m_bVisibleForEmptyFaction 0
   }
  }
  PS_FactionManualMarkerConfig "{5F34AC075861DF21}" {
   m_mManualMarkerConfig PS_ManualMarkerConfig "{5F34AC07AD94EA59}" {
    m_aVisibleForFactions {
     "US"
    }
    m_bVisibleForEmptyFaction 0
   }
  }
  PS_FactionManualMarkerConfig "{5F34AC077BC51BA0}" {
   m_mManualMarkerConfig PS_ManualMarkerConfig "{5F34AC07AD94EA59}" {
    m_aVisibleForFactions {
     "FIA"
    }
    m_bVisibleForEmptyFaction 0
   }
  }
  PS_FactionManualMarkerConfig "{69448AFED0259716}" {
   m_sFactionKey "UK"
   m_mManualMarkerConfig PS_ManualMarkerConfig "{5F34AC07AD94EA59}" {
    m_aVisibleForFactions {
     "UK"
    }
   }
  }
 }
}