SCR_MissionHeader {
 World "{C27B985DB42477DC}Worlds/Bellau/TelegraphRoad_Ep2.ent"
 SystemsConfig "{9D425D3FD7C3F521}Configs/Systems/LL_LobbySystems.conf"
 m_sName "Telegraph Road. Episode 2"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "After the heavy fighting for Losevo, the remnants of NAPA fall back to the neighbouring village of Borshchevo and wait for reinforcements. Meanwhile, Chernarussian Defence Forces units keep pushing north, deeper into NAPA-held territory. Chernarus, August 2021."
 m_sGameMode "TvT"
 m_iPlayerCount 128
}