SCR_MissionHeader {
 World "{5B6521C4A9C3464C}Worlds/Bellau/TelegraphRoad_Ep1.ent"
 SystemsConfig "{9D425D3FD7C3F521}Configs/Systems/LL_LobbySystems.conf"
 m_sName "Telegraph Road. Episode 1"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "Chernarussian Defence Forces assault units are reopening strategic communications near Belleau Wood, where NAPA formations hold their positions. Chernarus, August 2021."
 m_sGameMode "TvT"
 m_iPlayerCount 128
}