SCR_MissionHeader {
 World "{5C53639F0A5B6468}worlds/Zagoria/ABridgeTooFar.ent"
 m_sName "A Bridge Too Far"
 m_sAuthor "[TT]Jumbo"
 m_sDescription "Zagoria Region, Northern Jadrania — Summer 1990"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}