SCR_MissionHeader {
 World "{0F8C273A9712CD8C}Worlds/Armenhof/ArmenhofRaid_Mini.ent"
 m_sName "Armenhof Raid"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "FIA raid on Armenhof, captured by Soviet troops"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}