SCR_MissionHeader {
 World "{22D9B231F49E4E9C}Worlds/Armenhof/ArmenhofRaid.ent"
 m_sName "Armenhof Raid"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "FIA raid on Armenhof, captured by Soviet troops"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}