SCR_MissionHeader {
 World "{94124497CCDA32B2}worlds/Border/BorderBreakthrough_Episode1.ent"
 m_sName "Border Breakthrough. Episode 1"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "1989, Germany - Inner German Border (GDR–FRG)"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 118
 m_iStartingHours 5
 m_iStartingMinutes 33
}