SCR_MissionHeader {
 World "{0D0CFD0ED13D0322}worlds/Border/BorderBreakthrough_Episode2.ent"
 m_sName "Border Breakthrough. Episode 1"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "1989, Germany - Inner German Border (GDR–FRG)"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 115
 m_iStartingHours 14
 m_iStartingMinutes 44
}