SCR_MissionHeader {
 World "{37F7B6CA32901DFD}Worlds/Cain/KrasnyyAirfield.ent"
 m_sName "Krasnyy Airfield"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "On June 8, 1990, US Marines launch an amphibious assault on Kolguyev Island in the Barents Sea."
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 64
 m_eSaveTypes 0
}