SCR_MissionHeader {
 World "{6A8E8C50218EB612}Worlds/Cain/MalayaZemlya.ent"
 SystemsConfig "{9D425D3FD7C3F521}Configs/Systems/LL_LobbySystems.conf"
 m_sName "Malaya Zemlya"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "Soviet marines hold the coal port of Malaya Zemlya on Kolguyev against the UK"
 m_sGameMode "TvT"
 m_iPlayerCount 128
}
