SCR_MissionHeader {
 World "{996D4CFDE6F5A702}Worlds/Cain/PortSiege.ent"
 m_sName "Port Siege"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "The UK besieges a USSR port on Kolguev Island"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}