SCR_MissionHeader {
 World "{4CA90B4328A33004}Worlds/Rokostrov/TheIslandOfMisfortune_1.ent"
 m_sName "The Island of Misfortune. Part One"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "U.S. Marines assault a small Aegean island to destroy the Soviet signals-intelligence station and shore antenna, while the outnumbered Soviet garrison fights to hold them off."
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}