SCR_MissionHeader {
 World "{80BBDA5196F51074}worlds/Denali/FoxbatIncident.ent"
 m_sName "Foxbat Incident"
 m_sAuthor "[TT]Jumbo, [TT]Jidai"
 m_sDescription "USA, Alaska, 1990"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 110
 m_iStartingHours 5
}