SCR_MissionHeader {
 World "{B7E6DC50247F7A55}worlds/Wake/TuvankaBase.ent"
 m_sName "TuVaNkA Base"
 m_sAuthor "[TT]Jumbo"
 m_sDescription "8 июня 1990 года. Адриатическое море"
 m_sGameMode "#AR-Scenario_GameMode_GameMaster"
 m_iPlayerCount 128
}